In [1]:
import numpy as np

How to create an empty and a full NumPy array?

In [ ]:

np.empty((3,4), dtype =int) 

array([[31051392,        0,        0,        0],
       [       0,        0,        0,        0],
       [       0,        0,        0,        0]])

In [ ]:
np.full((3,4), 45, dtype = None)

array([[45, 45, 45, 45],
       [45, 45, 45, 45],
       [45, 45, 45, 45]])

Create a Numpy array filled with all zeros

In [ ]:
np.zeros( (3,4) )

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

Create a Numpy array filled with all ones

In [ ]:
np.ones( (3,4) )

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

Check whether a Numpy array contains a specified row

In [ ]:
x = np.array(([1,2,3,4], [5,6,7,10]))

In [ ]:
print([1, 2, 3, 4, 5] in x.tolist())

False


In [ ]:
print([5,6,7,10] in x.tolist())

True


How to Remove rows in Numpy array that contains non-numeric values?

In [ ]:
x= np.array(([2, 900, np.nan],
                  [777, 1, 1006]))

In [ ]:
print("Remove all rows containing non-numeric elements")
print(x[~np.isnan(x).any(axis=1)])

Remove all rows containing non-numeric elements
[[7.770e+02 1.000e+00 1.006e+03]]


Remove single-dimensional entries from the shape of an array

In [ ]:
x = np.ones((5, 1, 10))
print(np.squeeze(x).shape)

(5, 10)


Find the number of occurrences of a sequence in a NumPy array

In [ ]:
arr = np.random.rand(3,4)
  
# Counting sequence
#output = repr(arr).count("9, 4")
  
# view output
#print(output)

In [ ]:
arr

array([[0.51393392, 0.03296826, 0.26377149, 0.56600929],
       [0.04767559, 0.64046436, 0.37295466, 0.19182861],
       [0.77267588, 0.52162536, 0.74374567, 0.564138  ]])

In [ ]:
repr(arr).count('0.51393392, 0.03296826')

1

Find the most frequent value in a NumPy array

In [ ]:
x = np.array([6,6,7,7,7,8,8,8,8,2,2,2,2,4,5,2,8])
print("Original array:")
print(x)
  
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[6 6 7 7 7 8 8 8 8 2 2 2 2 4 5 2 8]
Most frequent value in the above array:
2


Combining a one and a two-dimensional NumPy Array

In [ ]:
num_1d = np.arange(10)
print("One dimensional array:")
print(num_1d)
  
num_2d = np.arange(20).reshape(2,10)
print("\nTwo dimensional array:")
print(num_2d)
  
for a, b in np.nditer([num_1d, num_2d]):
    print("%d:%d" % (a, b),)

One dimensional array:
[0 1 2 3 4 5 6 7 8 9]

Two dimensional array:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
0:0
1:1
2:2
3:3
4:4
5:5
6:6
7:7
8:8
9:9
0:10
1:11
2:12
3:13
4:14
5:15
6:16
7:17
8:18
9:19


How to build an array of all combinations of two NumPy arrays?

In [ ]:
array_1 = np.array([3,3,3,3,2,6])
array_2 = np.array([4,4,4,5,6,7])
  
print("Array-1")
print(array_1)

print(array_2)
  
comb_array = np.array(np.meshgrid(array_1, array_2)).T.reshape(-1, 2)
  
print("\nCombine array:")
print(comb_array)

Array-1
[3 3 3 3 2 6]
[4 4 4 5 6 7]

Combine array:
[[3 4]
 [3 4]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [3 4]
 [3 4]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [3 4]
 [3 4]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [3 4]
 [3 4]
 [3 4]
 [3 5]
 [3 6]
 [3 7]
 [2 4]
 [2 4]
 [2 4]
 [2 5]
 [2 6]
 [2 7]
 [6 4]
 [6 4]
 [6 4]
 [6 5]
 [6 6]
 [6 7]]


How to add a border around a NumPy array?

In [ ]:
array = np.zeros((6, 6))
  
print("Original array")
print(array)
  
print("with border")
  
array = np.pad(array, pad_width=1, mode='constant',
               constant_values=1)
  
print(array)

Original array
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
with border
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


How to compare two NumPy arrays?


In [ ]:
a = np.zeros((2,2))
b = np.ones((2,2))

np.array_equal(a, b)

False

How to check whether specified values are present in NumPy array?

In [ ]:
n_array = np.array([[5, 0, 9],
                    [3, 2, 1]])
 
print(10 in n_array)
print(20 in n_array)
print(6 in n_array)
print(2 in n_array)
print(0 in n_array)

False
False
False
True
True


How to get all 2D diagonals of a 3D NumPy array?

In [ ]:

arr = np.arange(5*5*5).reshape(5,5,5)
  
print("Original 3d array:\n", 
      arr)
  
# Create 2D diagonal array
diag_arr = np.diagonal(arr, 
                       axis1 = 1,
                       axis2 = 2)
  
print("2d diagonal array:\n", 
      diag_arr)

Original 3d array:
 [[[  0   1   2   3   4]
  [  5   6   7   8   9]
  [ 10  11  12  13  14]
  [ 15  16  17  18  19]
  [ 20  21  22  23  24]]

 [[ 25  26  27  28  29]
  [ 30  31  32  33  34]
  [ 35  36  37  38  39]
  [ 40  41  42  43  44]
  [ 45  46  47  48  49]]

 [[ 50  51  52  53  54]
  [ 55  56  57  58  59]
  [ 60  61  62  63  64]
  [ 65  66  67  68  69]
  [ 70  71  72  73  74]]

 [[ 75  76  77  78  79]
  [ 80  81  82  83  84]
  [ 85  86  87  88  89]
  [ 90  91  92  93  94]
  [ 95  96  97  98  99]]

 [[100 101 102 103 104]
  [105 106 107 108 109]
  [110 111 112 113 114]
  [115 116 117 118 119]
  [120 121 122 123 124]]]
2d diagonal array:
 [[  0   6  12  18  24]
 [ 25  31  37  43  49]
 [ 50  56  62  68  74]
 [ 75  81  87  93  99]
 [100 106 112 118 124]]


Flatten a Matrix in Python using NumPy

In [ ]:
arr.flatten()


array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124])

Flatten a 2d numpy array into 1d array

In [ ]:
x = np.random.rand(2,2)
  
x.flatten()
  


array([0.08638665, 0.69970929, 0.04975433, 0.59493004])

Move axes of an array to new positions

In [ ]:

arr = np.zeros((2, 3, 4))
arr.shape

(2, 3, 4)

In [ ]:
np.moveaxis(arr, -1, 0).shape

(4, 2, 3)

In [ ]:
np.transpose(arr).shape

(4, 3, 2)

In [ ]:
np.swapaxes(arr, 0, -1).shape

(4, 3, 2)

NumPy – Fibonacci Series using Binet Formula

In [ ]:
a = np.arange(1, 11)
lengthA = len(a)
  

sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2
  

Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print("The first {} numbers of Fibonacci series are {} . ".format(lengthA, Fn))

The first 10 numbers of Fibonacci series are [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.] . 


Counts the number of non-zero values in the array

In [ ]:
np.count_nonzero(a)

10

Count the number of elements along a given axis

In [ ]:
np.size(a, axis=0)

10

Trim the leading and/or trailing zeros from a 1-D array

In [ ]:
x = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
np.trim_zeros(x)


array([ 1,  5,  7,  0,  6,  2,  9,  0, 10])

Change data type of given numpy array

In [ ]:
x =  np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
x.dtype

dtype('int64')

In [ ]:
x.astype('float32')
x.dtype

dtype('int64')

Reverse a numpy array

In [ ]:
np.flipud(x) 

array([ 0,  0, 10,  0,  9,  2,  6,  0,  7,  5,  1,  0,  0,  0,  0])

How to make a NumPy array read-only?

In [ ]:
x.setflags(write=False)

Get the maximum value from given matrix

In [ ]:
np.max(x)

10

Get the minimum value from given matrix

In [ ]:
np.min(x)

0

Find the number of rows and columns of a given matrix using NumPy

In [ ]:
x.shape

(15,)

Select the elements from a given matrix

In [ ]:
x = np.arange(10)

condlist = [x<3, x>3]

choicelist = [x, x**2]

np.select(condlist, choicelist, 42)

array([ 0,  1,  2, 42, 16, 25, 36, 49, 64, 81])

Find the sum of values in a matrix

In [ ]:
x.sum()

45

Calculate the sum of the diagonal elements of a NumPy array

In [ ]:
x = np.ones((3,5))

np.trace(x)

3.0

Adding and Subtracting Matrices in Python

In [ ]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [ ]:
c = a-b
c

array([20, 29, 38, 47])

In [ ]:
d = a+c
d

array([40, 59, 78, 97])

Ways to add row/columns in numpy array

In [ ]:
x = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])

columnadd = np.array([[1], [2], [3]])
 
arr = np.concatenate([x, columnadd], axis=1)
 
print ("resultant array", str(arr))

resultant array [[ 1  2  3  1]
 [45  4  7  2]
 [ 9  6 10  3]]


In [ ]:
x = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
columnadd = np.array([[1], [2], [3]])

np.insert(x, 0, columnadd, axis =1)

array([[ 1,  2,  3,  1,  2,  3],
       [ 1,  2,  3, 45,  4,  7],
       [ 1,  2,  3,  9,  6, 10]])

Matrix Multiplication in NumPy

In [ ]:
b*a

array([  0,  30,  80, 150])

Get the eigen values of a matrix

In [ ]:
from numpy import linalg as LA
w, v = LA.eig(np.diag((1, 2, 3,4,5,6)))
w,v

(array([1., 2., 3., 4., 5., 6.]), array([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]]))

How to Calculate the determinant of a matrix using NumPy?

In [ ]:
np.linalg.det(x)

-73.99999999999983

How to inverse a matrix using NumPy

In [ ]:
np.linalg.inv(x)

array([[ 0.02702703,  0.02702703, -0.02702703],
       [ 5.22972973,  0.22972973, -1.72972973],
       [-3.16216216, -0.16216216,  1.16216216]])

How to count the frequency of unique values in NumPy array?

In [ ]:

ini_array = np.array([1,1,2,3,4,5,6,9,78])
  

unique, frequency = np.unique(ini_array, 
                              return_counts = True)

unique, frequency

(array([ 1,  2,  3,  4,  5,  6,  9, 78]), array([2, 1, 1, 1, 1, 1, 1, 1]))

Multiply matrices of complex numbers using NumPy in Python

In [ ]:
x = np.array([2+3j, 4+5j])

print(x)
  
y = np.array([8+7j, 5+6j])

print(y)
  

z = np.vdot(x, y)
z

[2.+3.j 4.+5.j]
[8.+7.j 5.+6.j]


(87-11j)

Compute the outer product of two given vectors using NumPy in Python

In [ ]:
array1 = np.array([3,4,5])
array2 = np.array([5,6,4])

print(array1)
print(array2)
  

result = np.outer(array1, array2)
result

[3 4 5]
[5 6 4]


array([[15, 18, 12],
       [20, 24, 16],
       [25, 30, 20]])

Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [ ]:
a = np.array([2, 6])
b = np.array([3, 10])
print("arrays :")
print("a = ", a)
print("\nb = ", b)
  

print("Inner product a and b =")
print(np.inner(a, b))
  
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])
print("\nMatrices :")
print("x =", x)
print("\ny =", y)
  
# Inner product of matrices
print("\nInner product  x and y =")
print(np.inner(x, y))

arrays :
a =  [2 6]

b =  [ 3 10]
Inner product a and b =
66

Matrices :
x = [[2 3 4]
 [3 2 9]]

y = [[ 1  5  0]
 [ 5 10  3]]

Inner product  x and y =
[[17 52]
 [13 62]]


Compute the covariance matrix of two given NumPy arrays

In [ ]:
np.cov(x, y)

array([[  1.        ,   3.        ,  -0.5       ,  -1.        ],
       [  3.        ,  14.33333333,  -7.5       , -11.        ],
       [ -0.5       ,  -7.5       ,   7.        ,   9.5       ],
       [ -1.        , -11.        ,   9.5       ,  13.        ]])

In [ ]:
np.cov(x,y,rowvar=False)

array([[ 0.5, -0.5,  2.5,  2. ,  2.5,  1.5],
       [-0.5,  0.5, -2.5, -2. , -2.5, -1.5],
       [ 2.5, -2.5, 12.5, 10. , 12.5,  7.5],
       [ 2. , -2. , 10. ,  8. , 10. ,  6. ],
       [ 2.5, -2.5, 12.5, 10. , 12.5,  7.5],
       [ 1.5, -1.5,  7.5,  6. ,  7.5,  4.5]])

Compute the Kronecker product of two mulitdimension NumPy arrays

In [ ]:
np.kron(x, y)

array([[ 2, 10,  0,  3, 15,  0,  4, 20,  0],
       [10, 20,  6, 15, 30,  9, 20, 40, 12],
       [ 3, 15,  0,  2, 10,  0,  9, 45,  0],
       [15, 30,  9, 10, 20,  6, 45, 90, 27]])

Convert the matrix into a list

In [ ]:
np.matrix.tolist(x)

[[2, 3, 4], [3, 2, 9]]

Replace NumPy array elements that doesn’t satisfy the given condition

In [ ]:
x = np.array([77, 88,1])


x[x < 50] = 99
  
x

array([77, 88, 99])

Return the indices of elements where the given condition is satisfied

In [ ]:
np.where(x>50)

(array([0, 1, 2]),)

Replace NaN values with average of columns

In [ ]:
x = np.array((1,2,3,np.nan))
x

array([ 1.,  2.,  3., nan])

In [ ]:
x[np.isnan(x)] = x[0:-1].mean()
x

array([1., 2., 3., 2.])

Replace negative value with zero in numpy array

In [ ]:
x = np.array([1, 2, -3, 4, -5, -6])
  


x[x<0] = 0
  

x

array([1, 2, 0, 4, 0, 0])

How to get values of an NumPy array at certain index positions?

In [ ]:
x1 = np.array([1, 10, 0, 30, 387])

  
x2 = np.array([25, 9, 1])

  
  
x1.put([0, 4], x2)
  
x1

array([25, 10,  0, 30,  9])

Find indices of elements equal to zero in a NumPy array

In [ ]:
n_array = np.array(([1, 0, 2,15,30, 3, 0, 0, 5,
                    6, 7, 5, 0, 81,2,4,6,7,0,6,34,0]))
  
np.where(n_array == 0)[0]


array([ 1,  6,  7, 12, 18, 21])

How to Remove columns in Numpy array that contains non-numeric values?

In [ ]:
x = np.array([[10,2,3,49, 22.5, np.nan],
                  [25,0,1,41, 52.5, np.nan]])
y = x[:, ~np.isnan(x).any(axis=0)]

y


array([[10. ,  2. ,  3. , 49. , 22.5],
       [25. ,  0. ,  1. , 41. , 52.5]])

How to access different rows of a multidimensional NumPy array?

In [ ]:
y[[1,1]]

array([[25. ,  0. ,  1. , 41. , 52.5],
       [25. ,  0. ,  1. , 41. , 52.5]])

Get row numbers of NumPy array having element larger than X

In [ ]:
np.where(np.any(y > 15,axis = 1))

(array([0, 1]),)

In [ ]:
a = np.zeros((5, 5), float)
np.fill_diagonal(a,7)
a

array([[7., 0., 0., 0., 0.],
       [0., 7., 0., 0., 0.],
       [0., 0., 7., 0., 0.],
       [0., 0., 0., 7., 0.],
       [0., 0., 0., 0., 7.]])

In [ ]:
print(2 in x)
print(0 in x)
print(6 in x)
print(50 in x)
print(10 in x)

True
True
False
False
True


Combined array index by index

In [ ]:
x = np.array([1, 2, 3, 4])

print(x[2] +x[3]) 

7


Find a matrix or vector norm using NumPy

In [ ]:
np.linalg.norm(x)

5.477225575051661

Calculate the QR decomposition of a given matrix using NumPy

In [ ]:
x = np.array([[10,67,88], [100,200,678]])
np.linalg.qr(x)

(array([[-0.09950372, -0.99503719],
        [-0.99503719,  0.09950372]]),
 array([[-100.49875621, -205.67418722, -683.39154224],
        [   0.        ,  -46.76674794,  -20.09975124]]))

Compute the condition number of a given matrix using NumPy

In [ ]:
np.linalg.cond(x)

18.39646422953988

Compute the eigenvalues and right eigenvectors of a given square array using NumPy?

In [ ]:
y = [[3, 6],
              [12, 15]]
np.linalg.eig(y)
  

(array([-1.39230485, 19.39230485]), array([[-0.80689822, -0.34372377],
        [ 0.59069049, -0.9390708 ]]))

Calculate the Euclidean distance using NumPy

In [ ]:
x = np.array([[5,6], [10, 20]])
np.linalg.norm(x - y)
 

5.744562646538029

Create a Numpy array with random values

In [ ]:
np.random.rand(3,4)

array([[0.13350723, 0.16628703, 0.79561777, 0.05150047],
       [0.44213757, 0.81734189, 0.81008651, 0.74720826],
       [0.23074778, 0.1303813 , 0.15640249, 0.74208105]])

How to choose elements from the list with different probability using NumPy?

In [ ]:
x = [1,2,3,4,5,6]
np.random.choice(x)

2

How to get weighted random choice in Python?

In [ ]:
from numpy.random import choice
  
sampleList = [100, 200, 300, 400, 500]
randomNumberList = choice(
  sampleList, 5, p=[0.05, 0.1, 0.15, 0.20, 0.5])
  
print(randomNumberList)

[500 400 500 500 100]


Generate Random Numbers From The Uniform Distribution using NumPy

In [ ]:
np.random.uniform(size=15)

array([0.41954736, 0.68848718, 0.62848686, 0.91672892, 0.85274909,
       0.00736824, 0.22095792, 0.77719707, 0.94307517, 0.51278084,
       0.86914245, 0.02061166, 0.07773959, 0.55005011, 0.38731653])

Get Random Elements form geometric distribution

In [ ]:
np.random.geometric(p=0.35,size=10)

array([5, 1, 8, 2, 5, 1, 1, 1, 1, 3])

Get Random Elements form laplace distribution

In [ ]:
np.random.laplace(0., 1., 150)

array([-0.26004543,  0.47624327, -1.47800604, -2.84878976,  3.37507215,
       -0.33574205, -0.32574572,  0.85083479,  0.55664871, -3.50923017,
        0.54888582,  0.56039546,  0.84734057,  0.02452351, -0.68959059,
       -2.90444995, -0.59219578,  0.48646081,  0.05158991, -0.36006038,
       -0.80964237, -0.41673378, -0.99158172, -1.38763636, -0.88258559,
       -0.16328328, -0.22238333,  0.19703339, -1.65739076,  0.14323278,
       -0.85630015,  0.73385925,  0.25408635,  0.45595954,  0.48277147,
       -0.52910531,  0.4730214 ,  1.28175475, -0.37307256, -1.85602223,
       -0.87870159, -0.82157686, -1.35700698, -0.35040842, -3.21036092,
        0.61769653,  3.02000288, -0.33787419,  1.00712248, -0.44124547,
        0.39079611, -4.35630942, -0.33469363,  0.05872319,  2.14659767,
        0.1931179 ,  0.28868359, -0.93086504,  0.3103907 ,  0.07402902,
        0.40778332, -1.80698386, -0.37259434,  2.0379426 , -1.2307927 ,
        0.53443645,  0.59111055, -1.33834533,  0.60656202, -0.44

Return a Matrix of random values from a uniform distribution

In [ ]:
import numpy.matlib
np.matlib.rand((5, 3), 4)

matrix([[0.54888437, 0.3213883 , 0.72776635],
        [0.70087586, 0.55970281, 0.84044184],
        [0.93370582, 0.94524378, 0.06840295],
        [0.25679226, 0.96400406, 0.09877433],
        [0.39014735, 0.91881134, 0.23496692]])

Return a Matrix of random values from a Gaussian distribution

In [ ]:
np.random.normal(4,5)

1.5001028400354972

How to get the indices of the sorted array using NumPy in Python?

In [ ]:
x = np.random.rand(1,15)

np.argsort(x)

array([[ 8, 13, 12,  6,  2,  9,  0,  5, 11,  4,  7, 10,  1,  3, 14]])

Finding the k smallest values of a NumPy array

In [ ]:
k = 3
x = np.sort(x)
x[:k]

array([[0.12532006, 0.21206122, 0.34851493, 0.36958463, 0.42098949,
        0.45656182, 0.68086608, 0.74640416, 0.75396595, 0.7658812 ,
        0.82383113, 0.84262096, 0.91494776, 0.92139266, 0.96874773]])

How to get the n-largest values of an array using NumPy?

In [9]:
x = np.array([2.1, 0,  1, 5,
                4, 1, 9])
sorted_index_array = np.argsort(x)
  

sorted_array = x[sorted_index_array]
  
k = 3
  
sorted_array[-k : ]

array([4., 5., 9.])

Sort the values in a matrix

In [10]:
np.sort(x)

array([0. , 1. , 1. , 2.1, 4. , 5. , 9. ])

Filter out integers from float numpy array

In [11]:
x[x != x.astype(int)]

array([2.1])

Find the indices into a sorted array

In [12]:
np.searchsorted([5,78,120,9,0,1,6,78,2], 3)

6

How to get element-wise true division of an array using Numpy?

In [13]:

 np.true_divide(x, 4)

array([0.525, 0.   , 0.25 , 1.25 , 1.   , 0.25 , 2.25 ])

How to calculate the element-wise absolute value of NumPy array?

In [14]:
np.absolute(x)
  

array([2.1, 0. , 1. , 5. , 4. , 1. , 9. ])

Compute the negative of the NumPy array

In [15]:
np.negative(x) 

array([-2.1, -0. , -1. , -5. , -4. , -1. , -9. ])

Multiply 2d numpy array corresponding to 1d array

In [16]:
a = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
b = np.array([0, 2, 3])

a* b[:, np.newaxis]

array([[ 0,  0,  0],
       [ 4,  8, 10],
       [ 3,  6,  9]])

Computes the inner product of two arrays

In [17]:
np.inner(a,b)

array([13, 23, 13])

Compute the nth percentile of the NumPy array

In [18]:
np.percentile(a, 75)

3.0

Calculate the n-th order discrete difference along the given axis

In [20]:
np.diff(a)

array([[1, 1],
       [2, 1],
       [1, 1]])

Calculate the sum of all columns in a 2D NumPy array

In [22]:
np.sum(x, axis = 0)

22.1

Calculate average values of two given NumPy arrays

In [26]:
a = np.random.randn(3,4)
b = np.random.randn(3,4)
np.mean([a,b], axis=0)

array([[-0.03075648, -0.42383747,  0.17388814,  0.36222469],
       [ 0.76948218,  0.24027531, -0.30293816, -1.64429845],
       [-0.73357975,  1.19618976, -0.30859865, -0.80075146]])

How to compute numerical negative value for all elements in a given NumPy array?

In [27]:
np.negative(a)

array([[-1.16447059,  0.22708317, -1.25846787, -0.64913035],
       [-2.36172413, -0.62577417, -0.4727639 ,  1.07351293],
       [-0.99127584, -0.95597721, -0.18511004,  0.75729886]])

How to get the floor, ceiling and truncated values of the elements of a numpy array?

In [28]:
np.floor(a)

array([[ 1., -1.,  1.,  0.],
       [ 2.,  0.,  0., -2.],
       [ 0.,  0.,  0., -1.]])

In [29]:
np.ceil(a)

array([[ 2., -0.,  2.,  1.],
       [ 3.,  1.,  1., -1.],
       [ 1.,  1.,  1., -0.]])

In [30]:
 np.trunc(a)

array([[ 1., -0.,  1.,  0.],
       [ 2.,  0.,  0., -1.],
       [ 0.,  0.,  0., -0.]])

How to round elements of the NumPy array to the nearest integer?

In [32]:
np.rint(a)

array([[ 1., -0.,  1.,  1.],
       [ 2.,  1.,  0., -1.],
       [ 1.,  1.,  0., -1.]])

Find the round off the values of the given matrix

In [35]:
np.matrix.round(b)

array([[-1., -1., -1.,  0.],
       [-1., -0., -1., -2.],
       [-2.,  1., -1., -1.]])

Determine the positive square-root of an array

In [36]:
np.sqrt(x)

array([1.44913767, 0.        , 1.        , 2.23606798, 2.        ,
       1.        , 3.        ])

Evaluate Einstein’s summation convention of two multidimensional NumPy arrays

In [40]:
a= np.array([[45, 23], [0, 12]])
b = np.array([[190, 1], [193, 489]])
np.einsum("mk,kn", a, b)

array([[12989, 11292],
       [ 2316,  5868]])