Imports

In [ ]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_breast_cancer

from sklearn.model_selection import train_test_split

Criando a classe perceptron

In [ ]:

class Perceptron():

  def __init__(self, n):
    #inicializando os pesos com valores aleatórios
    self.weights = np.random.rand(n,1)
  
  def train(self, X,Y, epochs, learning_rate):
    for  epoch in range(epochs):
      for i in range(X.shape[0]):
        yhat = self.predict(X[i])

        #regra de atualização dos pesos
        self.weights += learning_rate *(Y[i] - yhat)* X[i].reshape(-1,1)

        if i%100 == 0:
          print(f'EPOCH: {epoch}, iteration:{i}')
  
  def predict(self, X):
    z = np.dot(X.T, self.weights)
    return self.step_func(z)

  def step_func(self, z):
    return 1 if (z >= 0) else 0


Carregando dados do dataset Breast Cancer

In [ ]:
data = load_breast_cancer()

In [ ]:
data.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [ ]:
data.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [ ]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

Separando dados em treino e teste

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(data.data, data.target, test_size=0.2)

In [ ]:
X_train.shape

(455, 30)

Inicializando o modelo

In [ ]:
p = Perceptron(X_train.shape[1])

In [ ]:
p.weights

array([[0.49047834],
       [0.55209597],
       [0.79869381],
       [0.60538275],
       [0.03272068],
       [0.31084097],
       [0.88661888],
       [0.62485911],
       [0.02567885],
       [0.40418119],
       [0.77303378],
       [0.15207361],
       [0.86995154],
       [0.88380393],
       [0.41200211],
       [0.34922018],
       [0.80379806],
       [0.71157091],
       [0.08414572],
       [0.82921587],
       [0.313627  ],
       [0.3593875 ],
       [0.53387293],
       [0.7537799 ],
       [0.61602426],
       [0.74975346],
       [0.57335012],
       [0.13705061],
       [0.50382643],
       [0.1172793 ]])

Treinamento

In [ ]:
p.train(X = X_train,Y = y_train, epochs = 100, learning_rate = 0.01)

EPOCH: 0, iteration:0
EPOCH: 0, iteration:100
EPOCH: 0, iteration:200
EPOCH: 0, iteration:300
EPOCH: 0, iteration:400
EPOCH: 1, iteration:0
EPOCH: 1, iteration:100
EPOCH: 1, iteration:200
EPOCH: 1, iteration:300
EPOCH: 1, iteration:400
EPOCH: 2, iteration:0
EPOCH: 2, iteration:100
EPOCH: 2, iteration:200
EPOCH: 2, iteration:300
EPOCH: 2, iteration:400
EPOCH: 3, iteration:0
EPOCH: 3, iteration:100
EPOCH: 3, iteration:200
EPOCH: 3, iteration:300
EPOCH: 3, iteration:400
EPOCH: 4, iteration:0
EPOCH: 4, iteration:100
EPOCH: 4, iteration:200
EPOCH: 4, iteration:300
EPOCH: 4, iteration:400
EPOCH: 5, iteration:0
EPOCH: 5, iteration:100
EPOCH: 5, iteration:200
EPOCH: 5, iteration:300
EPOCH: 5, iteration:400
EPOCH: 6, iteration:0
EPOCH: 6, iteration:100
EPOCH: 6, iteration:200
EPOCH: 6, iteration:300
EPOCH: 6, iteration:400
EPOCH: 7, iteration:0
EPOCH: 7, iteration:100
EPOCH: 7, iteration:200
EPOCH: 7, iteration:300
EPOCH: 7, iteration:400
EPOCH: 8, iteration:0
EPOCH: 8, iteration:100
EPOCH: 8, 

Predição

In [ ]:
preds = []
for i in range(0,X_test.shape[0]):
  ypred = p.predict(X_test[i].reshape(-1,1))
  preds.append(ypred)

In [ ]:
from sklearn.metrics import accuracy_score
score = accuracy_score(y_test, preds)

In [ ]:
score

0.9473684210526315

Com a classe do Sklearn

In [ ]:
from sklearn.linear_model import Perceptron

clf = Perceptron(max_iter =100, eta0=0.01, random_state=0)
clf.fit(X_train, y_train)
pred = clf.predict(X_test)
score = accuracy_score(y_test, pred)
score


0.8947368421052632

### Explique o que você aprendeu em relação à taxa de aprendizagem, inicialização aleatória dos pesos e número de épocas.

- Taxa de Aprendizagem:
A taxa de aprendizagem é um hiper-parametro do perceptron que controla o quanto deve-se mudar o modelo dado um erro estimado que é calculado cada vez que os pesos são atualizados. A taxa de aprendizagem deve ser bem escolhida pois valores muito baixos podem resultar em treinamentos mais longos e valores muito altos podem resultar em treinamentos instáveis.

- Inicialização aleatória dos pesos: A inicialização dos pesos é uma tarefa importante em redes neurais profundas porque, dependendo de qual estratégia for utilizada para a inicialização dos pesos a rede pode demorar mais para convergir. Por exemplo, ao iniciar todos os pesos com valores 0 ou 1 a rede pode levar um tempo maior para convergir e com isso ter um gasto computacional maior. Uma das estratégias mais viáveis para a inicialização dos pesos é a inicialização aleatória que gere valores de uma distribuição gaussiana com média e desvio padrão 1.

- Número de épocas:
Corresponde a quantas vezes o perceptron irá realizar sua operação em cada dado da base de dados.